### ISSUE TITLE
Footnote on scroll (JS)

### ISSUE THREAD

**Issue by egikyan** [superKalo/truevault-website#76]
Works now on Chrome and Firefox, but not IE.

**Comment by superKalo** [comment]
има 7px разминаване и проблема е от custom шрифтовете и това че всеки браузър ги интерпретира по различен начин и съответно има ралика в line-height-а им. На теория дори колкото повече редове се съберат, толкова по-голяма става разликата. Може да се оправи с js-ти за IE конкретно, но май че не си струва усилията за сега ;-)

case solved, разбрахме от какво е, затварям задачата
